vjartexport_app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/run-cmd/{cmd}', function ($cmd) {
    return \Artisan::call($cmd);
});


Route::group(['namespace'=>'App\Http\Controllers'],function(){
    #Backend Routes
    Route::group(['prefix'=>'admin-control'],function()
    {
        Route::get('/login', 'AuthController@showLogin')->name('login');
        Route::post('/login', 'AuthController@login');
        Route::get('/logout', 'AuthController@logout')->name('logout');

        Route::group(['as'=>'admin.','middlewear' => 'auth'], function () {
            Route::get('/','DashboardController@dashboard')->name('dashboard');
    
            // Route::resources([
            //     'post/{post_type:slug}' => 'PostController',
            // ]);
            Route::get('{post_type:slug}', 'PostController@index')->name('post.index');
            Route::post('{post_type:slug}', 'PostController@store')->name('post.store');
            Route::get('{post_type:slug}/create', 'PostController@create')->name('post.create');
        }); 
    });


    #website Routes
    Route::group(['namespace'=>'web'],function() {
        Route::get('/','HomeController@index')->name('home');
        Route::get('about-us','AboutController@about')->name('about');
        Route::get('contact-us','ContactController@contact')->name('contact');
        // Route::get('products','ProductController@product')->name('product');
        Route::resource('product', 'ProductController')->only(['index', 'show']);
        // Route::get('blog','BlogController@blog')->name('blog');
        Route::resource('blog','BlogController')->only(['index','show']);
    });
});

vjartexport_app/app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
}

vjartexport_app/app/Models/PostType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PostType extends Model
{
    use HasFactory;
}

vjartexport_app/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\PostType;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PostType $post_type)
    {
        // dd($post_type);

        return view('backend.pages.post.index', compact('post_type'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(PostType $post_type)
    {
        return view('backend.pages.post.create',compact('post_type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,PostType $post_type,)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

vjartexport_app/resources/views/backend/pages/post/create.blade.php
@extends('backend.layouts.inner')

@section('site_title','Dashboard')

@section('content')

<div class="container py-4">
        <div class="bg-white">
            <h1>Page</h1>
            <h2>DashBoard/Services/Create</h2>
        </div>
        <form action="{{route('admin.post.store',[$post_type->slug])}}" method="post">
            @csrf
        <div class="row pt-5 bg-white">
            <div class="col-8  text-dark">
                <div class="row">
                    <div class="col-6">
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Title</label>
                            <input type="text" class="form-control" name="title" id="exampleFormControlInput1" placeholder="title">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Slug</label>
                            <input type="text" class="form-control" name="slug" id="exampleFormControlInput1" placeholder="slug">
                        </div>
                    </div>
                </div>
                
                
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Short Description</label>
                    <textarea class="form-control" name="excerpt" id="exampleFormControlTextarea1" rows="2"></textarea>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Description</label>
                    <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>

            </div>
                <div class="col-4 ">
                    <div class="card" style="width: 18rem;">
                        <img src="{{url('image/download.png')}}" class="card-img-top" alt="..." name="image">
                    </div>
                
                    <button class="btn btn-primary mt-3">Choose image</button>
                </div>
                <div class="row">
                    <div class="col-1">
                        <button type="submit" class="btn btn-primary">Save</button>

                    </div>
                    <div class="col-1">
                        <button type="button" class="btn btn-primary">Reset</button>

                    </div>
                </div>
        </div>
        </form>
    </div>

@endsection

vjartexport_app/resources/views/backend/pages/post/index.blade.php
<!-- @extends('backend.layouts.inner')

<h1>View {{ $post_type->name }}</h1> -->

@extends('backend.layouts.inner')

@section('site_title','Dashboard')

@section('content')

<div class="container">
    <div class="bgindex">
        <h1>Page</h1>
        <h2>DashBoard/Service/Index</h2>
    </div>
    
    <table class="table table-striped py-5">
  <thead>
    <tr>
      <th><input class="form-check-input" type="checkbox" value="" name="sr-no." >Sr .No</th>
      <th >Title</th>
      <th >Image</th>
      <th >Short Description</th>
      <th >Description</th>
    </tr>
  </thead>
  <tbody>
    @foreach($post_types as $index => $post_type)
    <tr>
      <th scope="row"><input class="form-check-input" type="checkbox" name="sr-no."></th>
      <td>{{ $post_type->name}}</td>
      <td>{{ $post_type->image}}</td>
      <td>{{ $post_type->excerpt}}</td>
      <td>{{ $post_type->description}}</td>
    </tr>
    @endforeach
  </tbody>
</table>
</div>

@endsection